// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQ_tddEBXI4y2AEp6oxi_rnzqPiqKlr4',
    appId: '1:131809757105:web:2efd8a514721bb98ce5f90',
    messagingSenderId: '131809757105',
    projectId: 'officeroute-96b30',
    authDomain: 'officeroute-96b30.firebaseapp.com',
    databaseURL: 'https://officeroute-96b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'officeroute-96b30.firebasestorage.app',
    measurementId: 'G-NC0330YSEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0twUhPfkynJW4dxVaNHsv6LA3nw5QF3k',
    appId: '1:131809757105:android:be45e50bf4155aabce5f90',
    messagingSenderId: '131809757105',
    projectId: 'officeroute-96b30',
    databaseURL: 'https://officeroute-96b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'officeroute-96b30.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXLZP5bGw-BhO5j_ZkFJuQgMZW9Qll6I',
    appId: '1:131809757105:ios:992de78e988d1cdbce5f90',
    messagingSenderId: '131809757105',
    projectId: 'officeroute-96b30',
    databaseURL: 'https://officeroute-96b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'officeroute-96b30.firebasestorage.app',
    androidClientId: '131809757105-tb2rkusnjq1u4tntrq14gonl4q2kne9i.apps.googleusercontent.com',
    iosClientId: '131809757105-q4ujnp8uutg49nkq72i5a5qahvbshm8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeroute',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuXLZP5bGw-BhO5j_ZkFJuQgMZW9Qll6I',
    appId: '1:131809757105:ios:992de78e988d1cdbce5f90',
    messagingSenderId: '131809757105',
    projectId: 'officeroute-96b30',
    databaseURL: 'https://officeroute-96b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'officeroute-96b30.firebasestorage.app',
    androidClientId: '131809757105-tb2rkusnjq1u4tntrq14gonl4q2kne9i.apps.googleusercontent.com',
    iosClientId: '131809757105-q4ujnp8uutg49nkq72i5a5qahvbshm8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeroute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMQ_tddEBXI4y2AEp6oxi_rnzqPiqKlr4',
    appId: '1:131809757105:web:a4beeff656934958ce5f90',
    messagingSenderId: '131809757105',
    projectId: 'officeroute-96b30',
    authDomain: 'officeroute-96b30.firebaseapp.com',
    databaseURL: 'https://officeroute-96b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'officeroute-96b30.firebasestorage.app',
    measurementId: 'G-G0SW8QR9LJ',
  );
}
